format_version: 3
pipelines:
  app: 
    group: defaultGroup
    materials:
      mygit: 
        git: git@github.com:videocursoscloud/vcc-curso-gocd.git
    stages: # list of stages in order
      - hello: 
          clean_workspace: true
          jobs:
            testJob: 
              tasks: 
               - exec: 
                   working_directory: app
                   command: make
                   arguments:
                    - hello
      - build: 
          clean_workspace: true
          jobs:
            testJob: 
              tasks: 
               - exec: 
                   working_directory: app
                   command: make
                   arguments:
                    - build
