format_version: 3
pipelines:
  testpipeline1: 
    group: defaultGroupp
    materials:
      mygit: 
        git: git@github.com:videocursoscloud/vcc-curso-gocd.git
    stages: # list of stages in order
      - testStage: 
          clean_workspace: true
          jobs:
            testJob: 
              tasks: 
               - exec: 
                   command: echo
                   arguments:
                    - "hello world"
