format_version: 3
pipelines:
  test:
    group: defaultGroup
    materials:
      git:
        git: https://github.com/videocursoscloud/Python-example-app.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - defaultStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
        jobs:
          defaultJob:
            tasks:
            - exec:
                arguments:
                - testfile
                  command: touch
                  run_if: passed
