format_version: 3
pipelines:
  test-nginx: 
    environment_variables:
      APP_NAME: test-nginx
    group: defaultGroup
    materials:
      mygit: 
        git: git@github.com:videocursoscloud/vcc-curso-gocd.git
    stages: # list of stages in order
      - hello: 
          clean_workspace: true
          jobs:
            testJob: 
              tasks: 
               - exec: 
                   working_directory: app
                   command: make
                   arguments:
                    - hello
      - build:
          clean_workspace: true
          artifacts:
            - external:
              id: docker
              store_id: mijack
              configuration:
                options:
                  Image: mijack/vcc-gocd-app
                  Tag: v${GO_TO_REVISION_MYGIT}
          jobs:
            testJob:
              tasks:
               - exec:
                   working_directory: app
                   command: make
                   arguments:
                    - build





