format_version: 3
pipelines:
  test-nginx: 
    environment_variables:
      APP_NAME: test-nginx
      GIT_SHORT_TAG=${GO_TO_REVISION_MYGIT[:8]}
      GIT_SHORT_TAG2=thisisatest
    group: defaultGroup
    materials:
      mygit: 
        git: git@github.com:videocursoscloud/vcc-curso-gocd.git
    stages: # list of stages in order
      - hello: 
          clean_workspace: true
          jobs:
            testJob: 
              tasks: 
               - exec: 
                   working_directory: app
                   command: make
                   arguments:
                    - hello
