format_version: 3 
pipelines:
  vcc-gocd-app:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    environment_variables:
      APP_NAME: vcc-gocd-app
    materials:
      mygit:
        git: git@github.com:videocursoscloud/vcc-curso-gocd.git
        auto_update: false
        branch: master
        name: mygit
